- name: install git
  apt: name=git
  tags: 
  - "git"
  - "install"
- name: git personal name
  git_config:
    name: user.name
    scope: global
    value: "Jojor"
  tags: 
  - "git"
  - "git-personal"
- name: git editor nvim
  git_config: 
    name: core.editor
    scope: global
    value: nvim
  tags: 
  - "git"
  - "git-personal"
